AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
